version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=mydb
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - mongo-network
    healthcheck:
      test: "netstat -an | grep -c 8081"
      interval: 20s
      timeout: 20s
      retries: 10
    depends_on:
      - mongodb

  data-pipeline-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-pipeline-api
    restart: always
    ports:
      - "13000:13000"
    networks:
      - mongo-network
    depends_on:
      - mongo-express
    stdin_open: true
    tty: true

  redoc:
    image: redocly/redoc
    environment:
      SPEC_URL: /openapi/gen/openapi.yml
    volumes:
      - ./docs/openapi/openapi.yml:/usr/share/nginx/html/openapi/gen/openapi.yml:ro
    ports:
      - "9194:80"
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge

volumes:
  mongodb_data: